CREATE TABLE IF NOT EXISTS measurements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  v_rms DOUBLE NOT NULL,
  i_rms DOUBLE NOT NULL,
  p_w DOUBLE NOT NULL,
  pf DOUBLE NOT NULL,
  PRIMARY KEY (id),
  INDEX (ts)
);
